name: CI - Train and Upload ML Artifacts

on:
  push:
    paths:
      - 'Workflow-CI/MLProject/**'
      - 'Membangun_model/modeling_ulfasyabania.py'
      - 'Preprocessing/ionosphere_preprocessing.csv'
  workflow_dispatch:

jobs:
  train-and-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run model training
        run: |
          python Workflow-CI/MLProject/modeling_ulfasyabania.py

      - name: Upload ML artifacts to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: ml-artifacts
          path: |
            mlartifacts/
            **/classification_report.txt
            **/model/
